# Generated by Django 4.1.5 on 2023-01-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_consumer',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Consumer'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_farmer',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Farmer'),
        ),
    ]
