# Generated by Django 4.1.5 on 2023-01-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_customer_name_alter_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='image',
            field=models.ImageField(default='ABC', upload_to='crop_images/'),
            preserve_default=False,
        ),
    ]
