# Generated by Django 4.1.5 on 2023-01-29 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_crop_desc_crop_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='order_date',
        ),
        migrations.AddField(
            model_name='order',
            name='deliver_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
